# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_comp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import yfinance as yf
import matplotlib.pyplot as plt
from PyQt5.QtWidgets import QMessageBox


class Ui_Stock_comp(object):
    def show(self):
        if self.stock_1.text() == "" or self.stock_2.text() == "":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)

            # setting message for Message Box
            msg.setText("Please enter a stock symbol")

            # setting Message box window title
            msg.setWindowTitle("Exception Error :(")

            # declaring buttons on Message Box
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)

            # start the app
            retval = msg.exec_()
            return
        # Define the stocks to compare
        stock1 = self.stock_1.text()
        stock2 = self.stock_2.text()

        # Download the data for the stocks
        stock1_data = yf.download(stock1)
        stock2_data = yf.download(stock2)

        # Plot the data for the stocks
        plt.figure(figsize=(20, 7))
        plt.plot(stock1_data['Close'], label=stock1)
        plt.plot(stock2_data['Close'], label=stock2)
        plt.xlabel('Date')
        plt.ylabel('Closing Price')
        plt.title('Comparison of Stock Prices')
        plt.legend()
        plt.grid(True)
        figManager = plt.get_current_fig_manager()
        figManager.window.showMaximized()
        plt.show()

    def setupUi(self, Stock_comp):
        Stock_comp.setObjectName("Stock_comp")
        Stock_comp.resize(800, 551)
        Stock_comp.setStyleSheet("background-color: rgb(0, 0, 0);")
        Stock_comp.setDocumentMode(False)
        Stock_comp.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Stock_comp)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 50, 361, 71))
        self.label.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                 "font: 15pt \"Comic Sans MS\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 160, 101, 71))
        self.label_2.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                   "font: 15pt \"Comic Sans MS\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 290, 101, 71))
        self.label_3.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                   "font: 15pt \"Comic Sans MS\";")
        self.label_3.setObjectName("label_3")
        self.stock_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.stock_1.setGeometry(QtCore.QRect(360, 160, 321, 71))
        self.stock_1.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                   "font: 15pt \"Comic Sans MS\";")
        self.stock_1.setText("")
        self.stock_1.setObjectName("stock_1")
        self.stock_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.stock_2.setGeometry(QtCore.QRect(360, 290, 321, 71))
        self.stock_2.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                   "font: 15pt \"Comic Sans MS\";")
        self.stock_2.setText("")
        self.stock_2.setObjectName("stock_2")
        self.show_graph = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.show())
        self.show_graph.setGeometry(QtCore.QRect(270, 420, 261, 71))
        self.show_graph.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                      "font: 15pt \"Comic Sans MS\";")
        self.show_graph.setObjectName("show_graph")
        Stock_comp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Stock_comp)
        self.statusbar.setObjectName("statusbar")
        Stock_comp.setStatusBar(self.statusbar)

        self.retranslateUi(Stock_comp)
        QtCore.QMetaObject.connectSlotsByName(Stock_comp)

    def retranslateUi(self, Stock_comp):
        _translate = QtCore.QCoreApplication.translate
        Stock_comp.setWindowTitle(_translate("Stock_comp", "MainWindow"))
        self.label.setText(_translate("Stock_comp", "Enter the stock symbols below"))
        self.label_2.setText(_translate("Stock_comp", "Stock 1:"))
        self.label_3.setText(_translate("Stock_comp", "Stock 2:"))
        self.show_graph.setText(_translate("Stock_comp", "Click to show graph"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Stock_comp = QtWidgets.QMainWindow()
    ui = Ui_Stock_comp()
    ui.setupUi(Stock_comp)
    Stock_comp.show()
    sys.exit(app.exec_())
