# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stock_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import yfinance as yf
import datetime
import pandas as pd
from PyQt5.QtWidgets import QApplication, QWidget, QTableWidget, QTableWidgetItem, QVBoxLayout, QLineEdit, QPushButton, \
    QMessageBox
from PyQt5 import QtCore


class Ui_stock_analysis(object):
    def get_data(self):
        if self.stock_name.text() == "" or self.date_1 == "" or self.date_2 == "" or self.interval == "":
            if self.stock_name.text() == "":
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)

                # setting message for Message Box
                msg.setText("Please enter a stock symbol")

                # setting Message box window title
                msg.setWindowTitle("Exception Error :(")

                # declaring buttons on Message Box
                msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)

                # start the app
                retval = msg.exec_()
                return
        stk = self.stock_name.text()

        stt = yf.Ticker(stk)  # Assigns ticker symbol to object

        # stt_info=stt.info('regularMarketPrice')
        # print(stt_info)
        star1 = self.date_1.text()
        en1 = self.date_2.text()
        interv1 = self.interval.text()

        perio1 = stt.history(start=star1, end=en1, interval=interv1)
        perio = pd.DataFrame(perio1)
        self.display_data(perio)

    def display_data(self, data):
        self.table.setRowCount(len(data))
        self.table.setColumnCount(len(data.columns))
        self.table.setHorizontalHeaderLabels(data.columns)
        for i, row in enumerate(data.itertuples()):
            for j in range(len(data.columns)):
                self.table.setItem(i, j, QTableWidgetItem(str(row[j + 1])))
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)

    def setupUi(self, stock_analysis):
        stock_analysis.setObjectName("stock_analysis")
        stock_analysis.resize(893, 883)
        stock_analysis.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(stock_analysis)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 50, 151, 41))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "font: 14pt \"Comic Sans MS\";")
        self.label.setObjectName("label")
        self.stock_name = QtWidgets.QLineEdit(self.centralwidget)
        self.stock_name.setGeometry(QtCore.QRect(490, 50, 201, 41))
        self.stock_name.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                      "font: 10pt \"Comic Sans MS\";")
        self.stock_name.setText("")
        self.stock_name.setObjectName("stock_name")
        self.show_data = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.get_data())
        self.show_data.setGeometry(QtCore.QRect(350, 390, 201, 61))
        self.show_data.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                     "font: 10pt \"Comic Sans MS\";")
        self.show_data.setObjectName("show_data")
        self.date_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.date_1.setGeometry(QtCore.QRect(490, 140, 201, 41))
        self.date_1.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                  "font: 10pt \"Comic Sans MS\";")
        self.date_1.setText("")
        self.date_1.setObjectName("date_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 140, 271, 41))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 14pt \"Comic Sans MS\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 230, 251, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 14pt \"Comic Sans MS\";")
        self.label_3.setObjectName("label_3")
        self.date_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.date_2.setGeometry(QtCore.QRect(490, 230, 201, 41))
        self.date_2.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                  "font: 10pt \"Comic Sans MS\";")
        self.date_2.setText("")
        self.date_2.setObjectName("date_2")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(70, 470, 751, 411))
        self.table.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                 "font: 10pt \"Comic Sans MS\";")
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        self.interval = QtWidgets.QLineEdit(self.centralwidget)
        self.interval.setGeometry(QtCore.QRect(490, 310, 201, 41))
        self.interval.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                    "font: 10pt \"Comic Sans MS\";")
        self.interval.setText("")
        self.interval.setObjectName("interval")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 310, 91, 41))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 14pt \"Comic Sans MS\";")
        self.label_4.setObjectName("label_4")
        stock_analysis.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(stock_analysis)
        self.statusbar.setObjectName("statusbar")
        stock_analysis.setStatusBar(self.statusbar)

        self.retranslateUi(stock_analysis)
        QtCore.QMetaObject.connectSlotsByName(stock_analysis)

    def retranslateUi(self, stock_analysis):
        _translate = QtCore.QCoreApplication.translate
        stock_analysis.setWindowTitle(_translate("stock_analysis", "Stock Analysis"))
        self.label.setText(_translate("stock_analysis", "Stock Symbol"))
        self.show_data.setText(_translate("stock_analysis", "Click to show data"))
        self.label_2.setText(_translate("stock_analysis", "Start Date(yyyy-mm-dd)"))
        self.label_3.setText(_translate("stock_analysis", "End Date(yyyy-mm-dd)"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("stock_analysis", "Open"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("stock_analysis", "High"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("stock_analysis", "Low"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("stock_analysis", "Close"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("stock_analysis", "Dividends"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("stock_analysis", "Stock Splits"))
        self.label_4.setText(_translate("stock_analysis", "Interval"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    stock_analysis = QtWidgets.QMainWindow()
    ui = Ui_stock_analysis()
    ui.setupUi(stock_analysis)
    stock_analysis.show()
    sys.exit(app.exec_())
